# Generated by Django 3.2.5 on 2021-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
